application: go-tour
version: 1
runtime: go
api_version: go1

default_expiration: "7d"

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /content/img
  static_dir: content/img
- url: /talks
  static_dir: talks
- url: /static/
  static_dir: static
- url: /(.*|list|lesson/.*|compile|fmt|script\.js)
  script: _go_app

nobuild_files: (solutions|content)/.*
