application: go-tour
version: 1
runtime: go
api_version: 3

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /compile
  script: _go_app
